name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: prev_version
        run: |
          echo "PREV_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name:  'Automated Version Bump'
        id: bump_version
        uses:  'phips28/gh-action-bump-version@v11.0.4'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording:  '#minor'
          major-wording:  '#major'
          patch-wording:  '#patch'

      - name: Get version
        id: new_version
        run: |
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin ghcr.io
          docker build -t ghcr.io/locistar/ato-deckbuilder-web:${{ env.NEW_VERSION }} .
          docker push ghcr.io/locistar/ato-deckbuilder-web:${{ env.NEW_VERSION }}
        if: env.PREV_VERSION != ${{ env.NEW_VERSION }}